# Name of your application. Used to uniquely configure containers.
service: shelf-smart

# Name of the container image.
image: ftyugihoj/shelf-smart

# Deploy to these servers.
servers:
  web:
    - 3.135.184.121
  # job:
  #   hosts:
  #     - 192.168.0.1
  #   cmd: bin/jobs

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Remove this section when using multiple web servers and ensure you terminate SSL at your load balancer.
#
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: shelfsmart.xyz
  # Proxy connects to your container on port 80 by default.
  app_port: 3000
  healthcheck:
    interval: 3
    path: /api/health
    timeout: 3

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: ftyugihoj

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD
    
# Configure builder setup.
builder:
  arch: amd64
  secrets:
    - DATABASE_URL
    - OPENAI_API_KEY
    - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    - CLERK_SECRET_KEY
    - CLERK_WEBHOOK_SIGNING_SECRET
    - NEXT_PUBLIC_BASE_URL
    - STRIPE_PUBLIC_KEY
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET
    - NEXT_PUBLIC_STRIPE_SAVANT_PRICE_ID
    - NEXT_PUBLIC_STRIPE_SCHOLAR_PRICE_ID
    - NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID
    - NEXT_PUBLIC_STRIPE_MANAGE_SUBSCRIPTION_URL
    - NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL
    - NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL
    - KAMAL_REGISTRY_PASSWORD
  # Pass in additional build args needed for your Dockerfile.
  # args:
  #   RUBY_VERSION: <%= ENV["RBENV_VERSION"] || ENV["rvm_ruby_string"] || "#{RUBY_ENGINE}-#{RUBY_ENGINE_VERSION}" %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - DATABASE_URL
    - OPENAI_API_KEY
    - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    - CLERK_SECRET_KEY
    - CLERK_WEBHOOK_SIGNING_SECRET
    - NEXT_PUBLIC_BASE_URL
    - STRIPE_PUBLIC_KEY
    - STRIPE_SECRET_KEY
    - STRIPE_WEBHOOK_SECRET
    - NEXT_PUBLIC_STRIPE_SAVANT_PRICE_ID
    - NEXT_PUBLIC_STRIPE_SCHOLAR_PRICE_ID
    - NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID
    - NEXT_PUBLIC_STRIPE_MANAGE_SUBSCRIPTION_URL
    - NEXT_PUBLIC_CLERK_SIGN_UP_FORCE_REDIRECT_URL
    - NEXT_PUBLIC_CLERK_SIGN_IN_FORCE_REDIRECT_URL
    - KAMAL_REGISTRY_PASSWORD

# Aliases are triggered with "bin/kamal <alias>". You can overwrite arguments on invocation:
# "bin/kamal app logs -r job" will tail logs from the first server in the job section.
#
# aliases:
#   shell: app exec --interactive --reuse "bash"

# Use a different ssh user than root
#
ssh:
  user: ubuntu
  keys:
    - ~/Downloads/key.pem
# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# asset_path: /app/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
#
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Use accessory services (secrets come from .kamal/secrets).
#
# accessories:
#   db:
#     image: mysql:8.0
#     host: 192.168.0.2
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: '%'
#       secret:
#         - MYSQL_ROOT_PASSWORD
#     files:
#       - config/mysql/production.cnf:/etc/mysql/my.cnf
#       - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
#     directories:
#       - data:/var/lib/mysql
#   redis:
#     image: valkey/valkey:8
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data
